import type { Metadata } from "next";
import { headers } from "next/headers";
import Link from "next/link";

import { AuditResults } from "@/components/audit-results";
import { generateAuditSummary } from "@/lib/audit/ai-summary";
import { buildAuditReport } from "@/lib/audit/engine";
import {
  createSpendStateFromPublicAudit,
  decodePublicAuditPayload,
} from "@/lib/audit/public-audit";
import { formatCurrency } from "@/lib/spend/summary";

type AuditPageProps = {
  params: {
    auditId: string;
  };
  searchParams: {
    s?: string | string[];
  };
};

const sharedTitle = "SpendLens — Your AI Spend Audit";

export function generateMetadata({
  params,
  searchParams,
}: AuditPageProps): Metadata {
  const payload = decodePublicAuditPayload(searchParams.s);
  const canonicalUrl = new URL(
    `/audit/${params.auditId}`,
    getRequestOrigin(),
  );

  if (typeof searchParams.s === "string") {
    canonicalUrl.searchParams.set("s", searchParams.s);
  }

  if (!payload) {
    return {
      title: sharedTitle,
      description: "SpendLens shows where an AI tool budget is leaking.",
      openGraph: {
        title: sharedTitle,
        description: "SpendLens shows where an AI tool budget is leaking.",
        type: "website",
        url: canonicalUrl,
      },
      twitter: {
        card: "summary_large_image",
        title: sharedTitle,
        description: "SpendLens shows where an AI tool budget is leaking.",
      },
    };
  }

  const report = buildAuditReport(createSpendStateFromPublicAudit(payload));
  const description =
    report.totalMonthlySavings < 100
      ? "You're spending well. SpendLens found no large defensible AI spend cuts."
      : `SpendLens found ${formatCurrency(
          report.totalMonthlySavings,
        )}/mo in defendable AI spend savings.`;

  return {
    title: sharedTitle,
    description,
    openGraph: {
      title: sharedTitle,
      description,
      type: "website",
      url: canonicalUrl,
    },
    twitter: {
      card: "summary_large_image",
      title: sharedTitle,
      description,
    },
  };
}

export default async function AuditPage({
  params,
  searchParams,
}: AuditPageProps) {
  const payload = decodePublicAuditPayload(searchParams.s);

  if (!payload) {
    return <InvalidAuditPage />;
  }

  const report = buildAuditReport(createSpendStateFromPublicAudit(payload));
  const summary = await generateAuditSummary(report);
  const shareUrl = buildShareUrl(params.auditId, searchParams.s);

  return (
    <AuditResults
      auditId={params.auditId}
      report={report}
      shareUrl={shareUrl}
      summary={summary}
    />
  );
}

function InvalidAuditPage() {
  return (
    <main className="flex min-h-screen items-center justify-center bg-[#f5f6f2] px-5 text-[#171512]">
      <section className="w-full max-w-lg rounded-lg border border-[#dedbd2] bg-white p-6 text-center shadow-sm">
        <p className="text-sm font-bold uppercase tracking-[0.16em] text-[#756f61]">
          SpendLens
        </p>
        <h1 className="mt-3 text-3xl font-semibold tracking-normal">
          This audit link is incomplete.
        </h1>
        <p className="mt-3 text-sm leading-6 text-[#6f695c]">
          Public audit links need the sanitized spend snapshot generated by the
          intake form. Start a fresh audit and share the new result URL.
        </p>
        <Link
          className="mt-5 inline-flex h-11 items-center justify-center rounded-lg bg-[#171512] px-4 text-sm font-bold text-white transition hover:bg-[#2a251f]"
          href="/"
        >
          Start new audit
        </Link>
      </section>
    </main>
  );
}

function buildShareUrl(auditId: string, payload: string | string[] | undefined) {
  const url = new URL(`/audit/${auditId}`, getRequestOrigin());

  if (typeof payload === "string") {
    url.searchParams.set("s", payload);
  }

  return url.toString();
}

function getRequestOrigin() {
  if (process.env.NEXT_PUBLIC_APP_URL) {
    return process.env.NEXT_PUBLIC_APP_URL;
  }

  const headerList = headers();
  const protocol = headerList.get("x-forwarded-proto") ?? "https";
  const host = headerList.get("host") ?? "localhost:3000";

  return `${protocol}://${host}`;
}
